apiVersion: v1
kind: Service
metadata:
  name: hello-polaris
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: hello-polaris
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: hello-polaris
  name: hello-polaris
spec:
  containers:
  - image: sckmkny/hello-polaris
    name: hello-polaris
    ports:
    - containerPort: 8080

