apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: hello-polaris
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: hello-polaris
status:
  loadBalancer: {}
---
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello-polaris
  name: hello-polaris
spec:
  containers:
  - image: sckmkny/hello-polaris
    name: hello-polaris
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
